CREATE ROLE avenirs_referentiel_formation_admin_role SUPERUSER;
CREATE ROLE avenirs_referentiel_formation_admin PASSWORD '9MyOyb33L3-' NOSUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
GRANT avenirs_referentiel_formation_admin_role to avenirs_referentiel_formation_admin;

CREATE DATABASE avenirs_referentiel_formation OWNER avenirs_referentiel_formation_admin;
GRANT ALL PRIVILEGES ON DATABASE avenirs_referentiel_formation TO avenirs_referentiel_formation_admin_role;
\c avenirs_referentiel_formation
CREATE SCHEMA IF NOT EXISTS dev AUTHORIZATION avenirs_referentiel_formation_admin;



